Repository SwiGs1/LiquidClaw13-Wasteland-Warfare, pull requests merged in 2020-02, with the labels that each got.

#18 Firearm additions - RCW and wattz1000/magneto
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  icons/fallout/objects/guns/energy.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  sound/f13weapons/rcw.ogg
  sound/f13weapons/wattz1000.ogg
  sound/f13weapons/wattz1000_magneto.ogg
Labels: Full Merge, Spriting, enhancement

#19 Adds Prickly Pears
  code/game/objects/structures/wasteplants.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/hydroponics/grown/prickly_pear.dm
  code/modules/vending/megaseed.dm
  icons/obj/flora/wastelandflora.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Full Merge, Spriting, enhancement

#20 Item additions - Stealthboys
  code/datums/actions/stealthboy_cloaking.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/stealthboy.dm
  code/modules/fallout/mob/simple_animal/mobs/nightkin.dm
  icons/mob/actions/actions_items.dmi
  icons/obj/device.dmi
  tgstation.dme
Labels: Full Merge, enhancement

#23 Clothing additions
  code/__DEFINES/construction.dm
  code/modules/clothing/suits/armor.dm
  code/modules/crafting/craft.dm
  code/modules/crafting/recipes.dm
  code/modules/crafting/tailoring.dm
Labels: enhancement

#24 URGENT !!Removes GhostEcho's cringe coat!! URGENT
  code/modules/clothing/suits/armor.dm
Labels: "Rebalance", Bug Fix, Full Merge, Mapping, Port, Removal, Spriting, Test Merge, WIP, bug, config update, documentation, duplicate, enhancement, error, good first issue, help wanted, invalid, question

#25 Message from God: I Have removed ERP from LiquidClaw13!!!!!! ft. Based Lads.
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_datums.dm
  interactions/lewd/lewd_interactions.dm
  interactions/lewd/lewd_species.dm
  interactions/lewd/objects.dm
Labels: "Rebalance", Full Merge, Removal, error, invalid

#26 New chems and medicine update
  code/game/objects/items/storage/firstaid.dm
  code/modules/crafting/recipes.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/fallout/objects/medicine/chemical.dmi
  icons/obj/chemical.dmi
  icons/obj/syringe.dmi
Labels: Spriting, WIP, enhancement

#27 The Armor Update
  code/modules/clothing/suits/armor.dm
  code/modules/crafting/tailoring.dm
  icons/fallout/clothing/suits.dmi
  icons/fallout/clothing_w/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: enhancement

#28 Removes Insect Armour
  code/modules/clothing/suits/armor.dm
  icons/fallout/clothing_w/suit.dmi
Labels: Removal

#30 Adds new drugs to drug spawns, Adds f13 foods to food spawns
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: "Rebalance", Full Merge, Removal, enhancement

#31 LC13 Mapping - Sunnydale Update and FEV BUNKER (The nightkin dungeon)
  _maps/_basemap.dm
  _maps/map_files/Pahrump/Pahrump.dmm
  _maps/map_files/SunnyDale/Dungeons.dmm
  _maps/map_files/SunnyDale/SunnyDale.dmm
  _maps/map_files/SunnyDale/job_changes.dm
  _maps/shuttles/fevbunker_elevator.dmm
  _maps/shuttles/northbunker_elevator.dmm
  _maps/sunnydale.dm
  _maps/sunnydale.json
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/world.dm
  code/modules/shuttle/f13.dm
  config/config.txt
  config/maps.txt
  config/motd.txt
  icons/turf/areas.dmi
  icons/turf/f13areas.dmi
  tgstation.dme
Labels: "Rebalance", Mapping, Removal, WIP, config update

#32 Adds Radio Host Role
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/den.dm
Labels: WIP, enhancement

#36 Bug Fix #35
  _maps/map_files/SunnyDale/Dungeons.dmm
  code/modules/crafting/recipes.dm
Labels: Bug Fix, Mapping

#38 Minor Mappping - NCR and Legion Base
  _maps/map_files/SunnyDale/SunnyDale.dmm
  _maps/shuttles/fevbunker_elevator.dmm
Labels: Mapping

#39 Swigs' Minor Mapping part two!
  _maps/map_files/SunnyDale/SunnyDale.dmm
  icons/fallout/clothing_w/suit.dmi
Labels: Bug Fix, Mapping, Spriting

#42 Tweaks and stuff
  code/__DEFINES/mobs.dm
  code/modules/fallout/obj/stack/hide.dm
  code/modules/fallout/obj/trash.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/jobs.dm
  code/modules/surgery/gender_reassignment.dm
Labels: "Rebalance", config update, enhancement, tweak

#43 Changes Recruit EXP times
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: "Rebalance", config update, tweak

#44 Several Mapping Changes
  _maps/map_files/SunnyDale/Dungeons.dmm
  _maps/map_files/SunnyDale/SunnyDale.dmm
Labels: Mapping, enhancement, tweak
